Replace TravisCI with GitHub Workflows
RockefellerArchiveCenter/styles pull request #230
Opened 2024-11-13 20:25 UTC by HaSistrunk

Replaces TravisCI with GitHub Workflow tests and deploys.

Includes a deploy file for the Style Guide (which is the Storybook site that serves to styles.rockarch.org) and the Style Library (which is our compiled CSS stylesheet and associated fonts and image assets, versioned to match the tagged release in GitHub) separately. The Style Guide should deploy on pushes to base, and the Style Library should only deploy when a new release is tagged on the base branch.

2024-11-13 20:58 UTC, p-galligan requested changes

2024-11-13 20:58 UTC, p-galligan commented on .github/workflows/dependencies.yml
This needs to be updated to use the GitHub token generator app.

2024-11-13 21:29 UTC, helrond commented on .github/workflows/dependencies.yml
> +          node-version: lts/iron
Can we not use the same version string we're using in workflows below: 'lts/*'?

2024-11-13 21:46 UTC, HaSistrunk commented on .github/workflows/dependencies.yml
> +          node-version: lts/iron
Yeah, that makes sense. I copied that from DIMES, which... maybe also needs an update?

2024-11-14 15:35 UTC, p-galligan commented on .github/workflows/dependencies.yml
> +          node-version: lts/iron
Yeah, I don't have strong feelings, but would argue that `lts/*` makes more sense to me.

2024-11-14 16:10 UTC, ioduok approved these changes

2024-11-14 22:46 UTC, helrond commented on .github/workflows/dependencies.yml
> +          node-version: lts/iron
Consistency is probably good. @p-galligan can you take a look at DIMES?

2024-11-15 13:35 UTC, p-galligan commented on .github/workflows/dependencies.yml
> +          node-version: lts/iron
> Consistency is probably good. @p-galligan can you take a look at DIMES?

This is done!

2024-11-15 16:54 UTC, helrond approved these changes

2024-11-18 19:58 UTC, p-galligan approved these changes

2024-11-18 19:59 UTC, merged